#!/bin/sh
#
# PROVIDE: mythtv
# REQUIRE: LOGIN 
# KEYWORD: shutdown
# $FreeBSD$
#
# Add the following lines to /etc/rc.conf to enable this service:
#
# mythtv_enable:            Set to NO by default. Set it to YES to enable it.
#                            a path.
# mythtv_user:              The user account mythtv daemon runs as
#

. /etc/rc.subr

name="mythtv"
rcvar=${name}_enable

pidfile=/var/run/MythTV/MythTV.pid
command=/usr/pbi/mythtv-`uname -m`/sbin/mythtv

load_rc_config $name

mythtv_user=${mythtv_user="root"}
_dirs="/var/run/MythTV /var/log/MythTV"
start_precmd="mkdir -p $_dirs; touch /var/run/MythTV/MythTV.pid; chown -R $mythtv_user $_dirs; ldconfig -m /usr/pbi/mythtv-`uname -m`/lib"
#RUN_AS_USER="mythtv"

command_args="$mythtv_args"

mythtv_stop()
{
        res=1
        echo -n 'Stopping mythtv.'
        if [ -f "${pidfile}" ]
        then
                kill -KILL $(cat "${pidfile}")
                rm -f ${pidfile}
                res=$?
        else
                killall -KILL mythtv
                res=$?
        fi

        echo
        return ${res}
}

stop_cmd='mythtv_stop'
run_rc_command "$1"

# Need to wait for Java to start before getting PID
#sleep 2
#pgrep -U root -f MythTV.jar > /var/run/MythTV/MythTV.pid
