#!/bin/sh
#

LOGFILE="/var/log/MythTV/MythTV.log"
MYTH_HOME="/usr/pbi/mythtv-`uname -m`"

# Check if Xvfb is enabled in config file created by GUI
XVFB_ENABLE=`grep Xvfb ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,Xvfb_Enable= ,,"`
echo $XVFB_ENABLE

# Need to check if Xvfb is running from another plugin and use that display
RUNNING_DISPLAY_ID=""
RUNNING_DISPLAY_ID=`pgrep -l -f Xvfb | sed -e "s,^[0-9].* *Xvfb ,," -e "s,-screen .*,,"`

# Check if mythtv-setup is enabled in config file created by GUI
Myth_Setup_ENABLE=`grep MythTV-Setup ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,MythTV-Setup_Enable= ,,"`
echo $Myth_Setup_ENABLE

# Check if mythtv-backend is enabled in config file created by GUI
Myth_Backend_ENABLE=`grep MythTV-Backend ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,MythTV-Backend_Enable= ,,"`
echo $Myth_Backend_ENABLE

# Get X DISPLAY setting from config file created by GUI
XDISPLAY=`grep "X11_Display= " ${MYTH_HOME}/etc/mythtv.conf | sed -e "s,X11_Display= ,,"`
#echo $XDISPLAY
DISPLAY=${XDISPLAY}
echo $DISPLAY

#if [ ! -f /var/run/MythTV/MythTV.pid ]; then
#    echo "No PIDfile found"
#else
#    id=`cat /var/run/MythTV/MythTV.pid`
#    #echo ${id}
#    if [ ! -z ${id} ];then
#        echo ${id}
#        echo "Existing PIDfile =" ${id} >> $LOGFILE
#        if ! ps -p ${id} >> $LOGFILE;then
#            echo "Another copy of MythTV might be running already." >> $LOGFILE
#            echo "Killing existing process if its running and restarting" >> $LOGFILE
#            kill -9 ${id}
#            rm -f /var/run/MythTV/MythTV.pid
#            echo "Deleted stale PIDfile"
#        fi
#    fi
#fi

# EXAMPLE setting DISPLAY for bash and csh
# export DISPLAY=:1
# setenv DISPLAY :1
# export DISPLAY=192.168.2.1:0.0
# setenv DISPLAY 192.168.2.1:0.0
#

# EXAMPLE of VNC using password authentication
# exec x11vnc -noshm -usepw -nevershared -forever -display :1

if [ $XVFB_ENABLE -eq 1 ]; then

    export DISPLAY=:1

    if [ -n "$RUNNING_DISPLAY_ID" ]
        echo "Existing Xvfb Display, using that." ${RUNNING_DISPLAY_ID}
        DISPLAY=${RUNNING_DISPLAY_ID}
        export DISPLAY
    fi

# If Xvfb is not already running, then start it.

    if [ -z `pgrep Xvfb` ]; then
        exec ${MYTH_HOME}/bin/Xvfb ${DISPLAY} -screen 0 1280x1024x16 &
    fi

# If x11vnc is not already running, then start it.

    if [ -z `pgrep x11vnc` ]; then
        exec ${MYTH_HOME}/bin/x11vnc -noshm -nevershared -forever -display :1 &
    fi

    if [ -z `pgrep fluxbox` ]; then
	# Need to make sure Xvfb has started before starting fluxbox
        sleep 1
        exec ${MYTH_HOME}/bin/fluxbox -d :1 &
    fi
fi

if [ $XVFB_ENABLE -ne 1 ]; then
    killall Xvfb x11vnc fluxbox
    export DISPLAY
    echo "Starting MythTV on DISPLAY:" >> $LOGFILE
    echo $DISPLAY >> $LOGFILE
fi

# Start the SQL database for MythTV
#/usr/pbi/mythtv-amd64/bin/mysql /usr/pbi/mythtv-amd64/_MythDatabase/mc.sql

# These 2 IF statements should be mutally exclusive

# Myth_Setup_ENABLE
if [ $Myth_Setup_ENABLE -eq 1 ]; then
    exec ${MYTH_HOME}/bin/mythtv-setup &
    #sleep 2
    #pgrep -U root -f MythTV.jar > /var/run/MythTV/MythTV.pid
fi

# Myth_Backend_ENABLE
if [ $Myth_Backend_ENABLE -eq 1 ]; then
    exec ${MYTH_HOME}/bin/mythbackend &
    #sleep 2
    #pgrep -U root -f MythTV.jar > /var/run/MythTV/MythTV.pid
fi
